### ISSUE TITLE
loss of sound in latest release

### ISSUE THREAD

**Issue by jmaris** [duffydack/linux-max98090#11]
Hey,

In the latest release, the soundcard is no longer detected again, not sure why.

Glad to hear the news about 4.15, great!  and thanks again for all your work in maintaining this until now :)
```
[    9.487179] max98090 i2c-193C9890:00: MAX98090 REVID=0x43
[    9.487942] max98090 i2c-193C9890:00: use default 2.8v micbias
[    9.488595] cht-bsw-max98090 cht-bsw-max98090: snd-soc-dummy-dai <-> media-cpu-dai mapping ok
[    9.488691] cht-bsw-max98090 cht-bsw-max98090: snd-soc-dummy-dai <-> deepbuffer-cpu-dai mapping ok
[    9.489673] cht-bsw-max98090 cht-bsw-max98090: HiFi <-> ssp2-port mapping ok
[    9.490932] input: chtmax98090 Headset Jack as /devices/pci0000:00/80860F28:00/cht-bsw-max98090/sound/card1/input8
```
It seems to be detected but then i get

`[   38.286770]  Audio Port: ASoC: no backend DAIs enabled for Audio Port`

**Comment by duffydack** [comment]
_Doh_
My fault again.  I started to use the cht_bsw_max98090 driver with the patches to enable it, but realised it needed the updated UCM (https://github.com/plbossart/UCM/tree/master/chtmax98090) to work (which 4.15rc2 doesn't btw), then lost track of things with being busy and forgot to fix it.  I was interested in hearing what people thought of the switch to the other (supported) driver since that's what it will use in 4.15... anyway, grab those files and put in /usr/share/alsa/ucm/chtmax98090

**Comment by jmaris** [comment]
I've just done that, on reboot i still have no sound strangely, give me a minute though, could be my fault :)

**Comment by duffydack** [comment]
I've only been using 4.15 tbh... I just installed 4.14 and sound is working.  That's different...

**Comment by ShinyRice** [comment]
I had no sound like he did, so after realising that in the latest patched kernel releases the max98090 driver was called chtmax98090 instead of byt-max98090, I decided to grab the UCM folder you linked us to and place it in the right folder. The result is that now I do have sound, but I have the same problem as other people do, this being having the audio sounding like coming out of a Dalek, stuttery and robotic. Is there anything that could be done to fix this? Audio was working just fine before 4.14.2, maybe 4.12.3.

**Comment by duffydack** [comment]
Interesting.  The daleks have always been a problem but I thought the patches and ucm would help.  I'll revert 4.14 back to old driver, and add 4.15rc for anyone that wants to test (stable for me).

**Comment by ShinyRice** [comment]
Okay, this is pretty strange. I think I've seen this sort of problem before, and the fix is similar to what I've done. When trying out older drivers, I still get Dalek audio, but restarting Pulseaudio (simply typing "pulseaudio" in the terminal) fixes that. With the newer drivers, (in the 4.14 kernels) Dalek audio can't be fixed by restarting it. Tried that out a few times, no luck. 4.15 also has Dalek audio, but I haven't tried to fix it.

**Comment by duffydack** [comment]
try removing .config/pulse and /var/lib/alsa/asound.state and restart pulse (systemctl --user restart pulseaudio)
I noticed it a bit more stable with the UCM tho..  you'll notice the mixers handled differently when using the UCM, in pavucontrol, the profiles.....  For me at least, I have to use alsamixer to view the alsa card (chtmax98090) and raise Speaker/Headphone to 100 and use pulse's Master to control, whereas before using master would also control alsa's speaker element..  Speaker/Headphone elements also reset every boot, so to set back to 100 on every boot you need to edit the hifi.conf file and at line 75 replace with cset "name='Speaker Volume' 100%"

**Comment by ShinyRice** [comment]
I tried out what you suggested with the 4.15 kernel you offered on the repo, it worked just fine for a while, but then it started doing Dalek sounds again. I still have the UCM folders in place.

**Comment by duffydack** [comment]
The patches to make the baytrail use cherrytrail doesn't really fix anything, other than allow us to use distros kernels again.  But that said I don't experience the daleks much, and only really when I run pavucontrol (sometimes).  I don't use inputs though, only earphones, but switching between speaker/headphone is painless as well now (used to break sound sometimes).
:(

**Comment by ShinyRice** [comment]
I've been playing around with some options in alsamixer, and now I don't have audio or I have a terrible crackling noise coming out of the speakers, so I believe I'm on to something. I think the key here is disabling duplex, making the audio driver just output audio instead of inputting and outputting, I've seen that mentioned in discussions about GalliumOS. In any case, I'll only make one more comment in order to report if this really was what's going on here.

**Comment by duffydack** [comment]
That's basically what I do, set PA to output only.  I used to have a rare problem when inserting headphones it would cause the daleks (PLL unlock) but that's not an issue anymore, even with output+input enabled, which is the default when using the UCM as the only choices are Default and Off.  I'm currently not using the UCM files as I don't see a need for them, yet.

**Comment by ShinyRice** [comment]
Alright, so in the end, I managed to get sound working in 4.14 kernels with the older driver, it seems that I had played around a bit too much with ALSA settings and I had channels muted. All I had to do was remove the UCM files and unmute those channels. This was to be expected, really, since it worked before as well. With the newer drivers and no UCM, well, Pulseaudio doesn't even detect the audio card, since it isn't present on pavucontrol, even though ALSA does see it. I'll fix that later, I can make do with the older drivers.
