### ISSUE TITLE
Add CONFIG_USB_NET_DRIVERS to config

### ISSUE THREAD

**Issue by JSkier21** [duffydack/linux-max98090#8]
I have an Ethernet USB dongle that needs this in the config. I can compile each release, however it wouldn't do much to add it into this kernel config, if you're okay with it.

**Comment by JSkier21** [comment]
Yikes, turns out there are a few modules with that. Looking specifically at USB2/3 support for ax88179_178a.

**Comment by duffydack** [comment]
Yeah, that's my 'tight' config used for 4.13.  I was trying to keep it under 50mb (github limit), but I have since used a default config for 4.14, stripped it, kept usb net drivers and kept under 50mb.  I'm hoping to forget about 4.13 and its problems this sunday if 4.14 stable is released (I've been using it for weeks).  I've kept 4.14 as much default I can, with usb net drivers and it's less than 40mb.

**Comment by duffydack** [comment]
yeah 4.14 is nov 12..  thank fk

**Comment by duffydack** [comment]
Weeeeeee. 4.14 is out

**Comment by JSkier21** [comment]
Thanks @duffydack, works great!
