### ISSUE TITLE
repo URL not working

### ISSUE THREAD

**Issue by d4l3k** [duffydack/linux-max98090#9]
I had this previously installed, but now the github repo link isn't working.

```
 ~  sudo pacman -Syu         
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
error: failed retrieving file 'duffydack.db' from github.com : The requested URL returned error: 404
error: failed to update duffydack (unexpected error)
```

Manually going to https://github.com/duffydack/linux-max98090/releases/download/current/ is returning a 404 too

**Comment by duffydack** [comment]
lol.  yeah, I got distracted while updating it, and ended up not updating it...

**Comment by d4l3k** [comment]
Seems to be working now. Thanks!

**Comment by duffydack** [comment]
sudo pacman -Syu linux-max98090 linux-max98090-headers
now using patches merged into 4.15 which means its not using legacy driver anymore, using cherrytrail..

give it a test

**Comment by 4e554c4c** [comment]
This seems to be happening again. Thanks for all the hard work by the way!

**Comment by duffydack** [comment]
Just updated the main page... 

"You need a UCM to get sound working in 4.15 (when it hits arch core), but only need it once.

git clone https://github.com/plbossart/UCM.git
sudo cp -R UCM/chtmax98090 /usr/share/alsa/ucm/
then reboot. verify mixers aren't muted in alsamixer. once you verified it all works, remove the folder. Why? Because it changes the way it handles your mixers, so just remove it. trust me.

Now you can remove my pkg and the repo, it's obsolete."

**Comment by 4e554c4c** [comment]
Ok thanks :)
